"""
01_StackedLSTM_실습.ipynb 조립 스크립트
각 셀을 여기서 리스트로 관리하고, 마지막에 JSON 으로 덤프한다.
Write 툴로 대형 JSON 을 직접 쓰면 오타/이스케이프 위험이 커서 이 방식이 안전하다.
"""
import json
from pathlib import Path

# ---------------------------------------------------------------------------
# 셀 도우미
# ---------------------------------------------------------------------------
def md(*lines: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": "\n".join(lines),
    }

def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": "\n".join(lines),
    }

cells: list[dict] = []

# ---------------------------------------------------------------------------
# 타이틀 + 개요
# ---------------------------------------------------------------------------
cells.append(md(
    "# 4.1 Stacked LSTM + Dropout — 실습",
    "",
    "COL-BL v2.4 프로젝트의 Week 4.1 실습. 3주차에서 배운 **단일 LSTM + 정규화 (3.5)** 를 ",
    "**다층 구조** 로 확장하면 실제로 무슨 일이 일어나는지 네 가지 실험으로 확인한다.",
    "",
    "## 이 노트북의 목적",
    "",
    "1. **num_layers 를 1 → 3 으로 늘리면 성능이 따라서 올라갈까?** — 직관 검증",
    "2. **깊이 축에서 gradient vanishing 이 실제 관측되는가?** — `register_hook` 로 층별 gradient norm 을 측정",
    "3. **Variational Dropout + 층별 LayerNorm 을 쓰면 3층이 살아나는가?** — 3.5 이론의 실전 검증",
    "4. **어떤 IMF 에 몇 층이 적합할지** 4.3 Optuna 탐색을 위한 사전 가설 수립",
    "",
    "## 실험 설계 요약",
    "",
    "| 실험 | 모델 | 비교 축 | 기대 결과 |",
    "|---|---|---|---|",
    "| §3 실험 1 | `nn.LSTM(dropout=0)` plain | 1 vs 2 vs 3층 | 3층에서 학습 불안정 또는 조기 과적합 |",
    "| §4 실험 2 | 실험 1 의 3층 모델 | 층별 gradient norm | 입력 쪽 층 gradient 가 출력 쪽 대비 작음 |",
    "| §5 실험 3 | Variational Dropout + 층별 LN | 1 vs 2 vs 3층 | 3층이 정상 수렴 |",
    "| §6 실험 4 | 실험 1 vs 실험 3 의 3층 | plain vs regularized | regularized 쪽이 val loss 우위 |",
    "",
    "## 재활용 자산",
    "",
    "- **3.4 §16 의 `train_one_individual(params) → best_val_loss`** 인터페이스 — 그대로 재사용",
    "- **3.5 §2 의 `VariationalDropout` 클래스** — §5 실험 3 에서 이식",
    "- MSFT 일봉 데이터 (yfinance) — 3.4 실습과 동일 데이터",
    "",
    "> 주의: 이 노트북은 실행 검증을 로컬 환경에서 수행한다 (CLAUDE.md 지침). 실행 전 `torch`, `yfinance`, `koreanize-matplotlib` (Linux 만) 설치 필요.",
))

# ---------------------------------------------------------------------------
# §1. 셋업
# ---------------------------------------------------------------------------
cells.append(md(
    "---",
    "",
    "## §1. 셋업",
    "",
    "필수 import, 한글 폰트 설정 (CLAUDE.md 지침), seed 고정, device 탐지까지 한 번에.",
))

cells.append(code(
    "# ---- 필수 라이브러리 ----",
    "import numpy as np",
    "import pandas as pd",
    "import torch",
    "import torch.nn as nn",
    "from torch.utils.data import DataLoader, TensorDataset",
    "import matplotlib.pyplot as plt",
    "import platform",
    "import random",
    "import copy",
    "",
    "# ---- 한글 폰트 (CLAUDE.md 필수 지침) ----",
    "if platform.system() == 'Windows':",
    "    plt.rcParams['font.family'] = 'Malgun Gothic'",
    "elif platform.system() == 'Darwin':  # Mac",
    "    plt.rcParams['font.family'] = 'AppleGothic'",
    "else:  # Linux (샌드박스 환경)",
    "    import koreanize_matplotlib  # pip install koreanize-matplotlib --break-system-packages",
    "    plt.rcParams['font.family'] = 'NanumGothic'",
    "plt.rcParams['axes.unicode_minus'] = False  # 마이너스 기호 깨짐 방지",
    "",
    "# ---- Reproducibility ----",
    "SEED = 42",
    "random.seed(SEED)",
    "np.random.seed(SEED)",
    "torch.manual_seed(SEED)",
    "if torch.cuda.is_available():",
    "    torch.cuda.manual_seed_all(SEED)",
    "",
    "# ---- Device 탐지 ----",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')",
    "print(f'PyTorch: {torch.__version__}')",
    "print(f'device : {device}')",
))

# ---------------------------------------------------------------------------
# §1.2 데이터 로드
# ---------------------------------------------------------------------------
cells.append(md(
    "### §1.2 MSFT 일봉 로드 + 윈도우화",
    "",
    "- **타겟**: 다음 날 로그수익률 $r_{t+1} = \\log(P_{t+1}/P_t)$",
    "- **입력 피처 (10종)**: 로그수익률, 거래량 변화율, 종가/MA5, 종가/MA20, 고가-저가 범위, ",
    "  볼린저 폭, RSI, MACD, 20일 변동성, 이전일 수익률 (간이 피처 — 본 프로젝트 피처 엔지니어링은 Week 2 산출)",
    "- **윈도우**: 60일 lookback → 1일 예측",
    "- **학습/검증 분할**: 시간순 80/20 (Walk-Forward 정식 분할은 Week 6 에서 적용)",
))

cells.append(code(
    "import yfinance as yf",
    "",
    "# ---- MSFT 일봉 다운로드 ----",
    "ticker = 'MSFT'",
    "df = yf.download(ticker, start='2010-01-01', end='2024-12-31', auto_adjust=True, progress=False)",
    "",
    "# yfinance 가 MultiIndex 로 반환하는 버전 대응",
    "if isinstance(df.columns, pd.MultiIndex):",
    "    df.columns = df.columns.get_level_values(0)",
    "",
    "print(f'기간: {df.index.min().date()} ~ {df.index.max().date()} ({len(df)} 일)')",
    "df.head(3)",
))

cells.append(code(
    "# ---- 간이 피처 엔지니어링 (10차원) ----",
    "# 주의: 실전 COL-BL 은 Week 2 에서 만든 피처셋을 사용. 여기서는 4.1 실험 목적으로 간소화",
    "close = df['Close']",
    "volume = df['Volume']",
    "high, low = df['High'], df['Low']",
    "",
    "feat = pd.DataFrame(index=df.index)",
    "feat['log_ret'] = np.log(close / close.shift(1))",
    "feat['vol_chg'] = volume.pct_change()",
    "feat['price_ma5'] = close / close.rolling(5).mean() - 1",
    "feat['price_ma20'] = close / close.rolling(20).mean() - 1",
    "feat['hl_range'] = (high - low) / close",
    "",
    "# 볼린저 폭",
    "ma20, std20 = close.rolling(20).mean(), close.rolling(20).std()",
    "feat['bb_width'] = (4 * std20) / ma20",
    "",
    "# RSI (간이)",
    "delta = close.diff()",
    "up = delta.clip(lower=0).rolling(14).mean()",
    "down = (-delta.clip(upper=0)).rolling(14).mean()",
    "rs = up / (down + 1e-9)",
    "feat['rsi'] = 100 - 100 / (1 + rs)",
    "",
    "# MACD (간이)",
    "ema12 = close.ewm(span=12).mean()",
    "ema26 = close.ewm(span=26).mean()",
    "feat['macd'] = (ema12 - ema26) / close",
    "",
    "# 20일 변동성",
    "feat['vol20'] = feat['log_ret'].rolling(20).std()",
    "",
    "# 이전일 수익률",
    "feat['prev_ret'] = feat['log_ret'].shift(1)",
    "",
    "# 타겟: 다음 날 로그수익률",
    "target = feat['log_ret'].shift(-1)",
    "",
    "# 결측 제거",
    "data = pd.concat([feat, target.rename('target')], axis=1).dropna()",
    "print(f'사용 가능한 표본: {len(data)} 일')",
    "print(f'피처 차원: {feat.shape[1]}')",
    "data.head(3)",
))

cells.append(code(
    "# ---- 표준화 (train 구간 통계로만 적합; look-ahead 금지) ----",
    "split_idx = int(len(data) * 0.8)",
    "",
    "X_all = data[feat.columns].values.astype(np.float32)  # (T, D)",
    "y_all = data['target'].values.astype(np.float32)       # (T,)",
    "",
    "mu = X_all[:split_idx].mean(axis=0)",
    "sd = X_all[:split_idx].std(axis=0) + 1e-8",
    "X_std = (X_all - mu) / sd",
    "",
    "y_mu = y_all[:split_idx].mean()",
    "y_sd = y_all[:split_idx].std() + 1e-8",
    "y_std = (y_all - y_mu) / y_sd",
    "",
    "print(f'피처 평균 (train): {mu.round(3)}')",
    "print(f'피처 표준편차 (train): {sd.round(3)}')",
    "print(f'타겟 평균 (train): {y_mu:.5f}, 표준편차: {y_sd:.5f}')",
))

cells.append(code(
    "# ---- 시퀀스 윈도우 생성 ----",
    "WINDOW = 60  # lookback",
    "",
    "def make_windows(X: np.ndarray, y: np.ndarray, window: int):",
    "    '''(T, D) → (N, window, D), (N,)'''",
    "    Xs, ys = [], []",
    "    for i in range(len(X) - window):",
    "        Xs.append(X[i : i + window])",
    "        ys.append(y[i + window - 1])  # 윈도우 마지막 날 기준 다음날 예측 타겟",
    "    return np.array(Xs), np.array(ys)",
    "",
    "X_win, y_win = make_windows(X_std, y_std, WINDOW)",
    "print(f'윈도우 shape: X={X_win.shape}, y={y_win.shape}')",
    "",
    "# ---- train/val 시간순 분할 ----",
    "# 주의: 윈도우 생성 후에도 split 은 **시간순** 이어야 한다",
    "split_win = int(len(X_win) * 0.8)",
    "X_tr, y_tr = X_win[:split_win], y_win[:split_win]",
    "X_va, y_va = X_win[split_win:], y_win[split_win:]",
    "print(f'train: {X_tr.shape}, val: {X_va.shape}')",
))

cells.append(code(
    "# ---- DataLoader 구성 ----",
    "BATCH = 64",
    "",
    "train_ds = TensorDataset(torch.from_numpy(X_tr), torch.from_numpy(y_tr))",
    "val_ds   = TensorDataset(torch.from_numpy(X_va), torch.from_numpy(y_va))",
    "",
    "train_loader = DataLoader(train_ds, batch_size=BATCH, shuffle=True, drop_last=False)",
    "val_loader   = DataLoader(val_ds,   batch_size=BATCH, shuffle=False, drop_last=False)",
    "",
    "INPUT_DIM = X_tr.shape[2]  # 피처 수 (10)",
    "print(f'input_dim = {INPUT_DIM}, batch = {BATCH}')",
    "print(f'train batches = {len(train_loader)}, val batches = {len(val_loader)}')",
))

# ---------------------------------------------------------------------------
# §2. 공통 유틸
# ---------------------------------------------------------------------------
cells.append(md(
    "---",
    "",
    "## §2. 공통 유틸 — `train_one_individual`",
    "",
    "3.4 §16 에서 설계한 함수를 그대로 재활용한다. **모델·에폭·lr 만 인자로 바꾸고** 내부 학습 루프는 동일 ",
    "→ 이 노트북의 모든 실험은 같은 학습 루프를 쓴다 (변인 통제).",
    "",
    "반환값은 `(best_val_loss, loss_history)`:",
    "- `best_val_loss`: 이 설정의 최종 점수 (Optuna objective 가 받는 값)",
    "- `loss_history`: 에폭별 `(train_loss, val_loss)` 리스트 — 학습곡선 플롯용",
))

cells.append(code(
    "def train_one_individual(model, epochs=30, lr=1e-3, weight_decay=1e-4,",
    "                         max_norm=1.0, patience=10, verbose=False):",
    "    '''단일 모델을 학습하고 best_val_loss 와 loss history 를 반환.",
    "    3.4 §16 인터페이스의 간소화 버전.'''",
    "    model = model.to(device)",
    "    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)",
    "    loss_fn = nn.MSELoss()",
    "",
    "    best_val = float('inf')",
    "    best_state = None",
    "    stale = 0",
    "    history = []",
    "",
    "    for epoch in range(epochs):",
    "        # ---- train ----",
    "        model.train()",
    "        tr_losses = []",
    "        for xb, yb in train_loader:",
    "            xb, yb = xb.to(device), yb.to(device)",
    "            optimizer.zero_grad()",
    "            pred = model(xb)",
    "            loss = loss_fn(pred, yb)",
    "            loss.backward()",
    "            nn.utils.clip_grad_norm_(model.parameters(), max_norm=max_norm)",
    "            optimizer.step()",
    "            tr_losses.append(loss.item())",
    "",
    "        # ---- val ----",
    "        model.eval()",
    "        va_losses = []",
    "        with torch.no_grad():",
    "            for xb, yb in val_loader:",
    "                xb, yb = xb.to(device), yb.to(device)",
    "                pred = model(xb)",
    "                va_losses.append(loss_fn(pred, yb).item())",
    "",
    "        tr = np.mean(tr_losses)",
    "        va = np.mean(va_losses)",
    "        history.append((tr, va))",
    "",
    "        if va < best_val:",
    "            best_val = va",
    "            best_state = copy.deepcopy(model.state_dict())",
    "            stale = 0",
    "        else:",
    "            stale += 1",
    "",
    "        if verbose and (epoch % 5 == 0 or epoch == epochs - 1):",
    "            print(f'  epoch {epoch:3d} | train {tr:.5f} | val {va:.5f} | best {best_val:.5f}')",
    "",
    "        if stale >= patience:",
    "            if verbose:",
    "                print(f'  early stop at epoch {epoch}')",
    "            break",
    "",
    "    if best_state is not None:",
    "        model.load_state_dict(best_state)",
    "    return best_val, history, model",
))

cells.append(code(
    "def count_params(model):",
    "    '''학습 가능한 파라미터 수 세기'''",
    "    return sum(p.numel() for p in model.parameters() if p.requires_grad)",
    "",
    "def reset_seed(seed=SEED):",
    "    '''실험 간 동일 초기화를 위해 매번 호출'''",
    "    random.seed(seed)",
    "    np.random.seed(seed)",
    "    torch.manual_seed(seed)",
    "    if torch.cuda.is_available():",
    "        torch.cuda.manual_seed_all(seed)",
))

# ---------------------------------------------------------------------------
# §3. 실험 1
# ---------------------------------------------------------------------------
cells.append(md(
    "---",
    "",
    "## §3. 실험 1 — Plain `nn.LSTM` 1 vs 2 vs 3층 비교",
    "",
    "**관찰 포인트:**",
    "",
    "1. 깊이를 늘리면 **파라미터 수가 선형이 아니라 $O(\\text{num\\_layers} \\cdot H^2)$** 로 증가 — 얼마나?",
    "2. val loss 는 층수에 비례해서 좋아질까? (직관 검증)",
    "3. 3층에서 **학습 불안정** 또는 **조기 과적합** 이 나타나는가?",
    "",
    "조건: 모든 모델에 `hidden=64`, 같은 lr·epoch·seed, `dropout=0` (정규화는 §5 에서 추가).",
))

cells.append(code(
    "class PlainLSTMRegressor(nn.Module):",
    "    '''Plain Stacked LSTM — 정규화 없이 깊이만 변경.",
    "    마지막 시점 hidden 을 선형 사상으로 스칼라 출력.'''",
    "    def __init__(self, input_size, hidden_size, num_layers):",
    "        super().__init__()",
    "        self.lstm = nn.LSTM(",
    "            input_size=input_size,",
    "            hidden_size=hidden_size,",
    "            num_layers=num_layers,",
    "            batch_first=True,",
    "            dropout=0.0,  # 실험 1 에서는 정규화 없음",
    "        )",
    "        self.head = nn.Linear(hidden_size, 1)",
    "",
    "    def forward(self, x):",
    "        out, _ = self.lstm(x)         # (B, T, H)",
    "        last = out[:, -1, :]          # 마지막 시점 (B, H)",
    "        return self.head(last).squeeze(-1)  # (B,)",
))

cells.append(code(
    "# ---- 1/2/3층 모델 학습 ----",
    "HIDDEN = 64",
    "EPOCHS = 40",
    "LR = 1e-3",
    "",
    "plain_results = {}  # {num_layers: (best_val, history, model)}",
    "",
    "for L in [1, 2, 3]:",
    "    reset_seed()",
    "    model = PlainLSTMRegressor(INPUT_DIM, HIDDEN, num_layers=L)",
    "    n_params = count_params(model)",
    "    print(f'\\n=== Plain LSTM {L}층 ({n_params:,} params) ===')",
    "    best_val, hist, trained = train_one_individual(model, epochs=EPOCHS, lr=LR, verbose=True)",
    "    plain_results[L] = (best_val, hist, trained, n_params)",
    "",
    "print('\\n=== 실험 1 요약 ===')",
    "for L, (best, hist, _, n_params) in plain_results.items():",
    "    print(f'{L}층 | params={n_params:>7,} | best_val_loss={best:.5f}')",
))

cells.append(code(
    "# ---- 학습곡선 비교 플롯 ----",
    "fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))",
    "",
    "for L, (_, hist, _, _) in plain_results.items():",
    "    tr = [h[0] for h in hist]",
    "    va = [h[1] for h in hist]",
    "    axes[0].plot(tr, label=f'{L}층', alpha=0.85)",
    "    axes[1].plot(va, label=f'{L}층', alpha=0.85)",
    "",
    "axes[0].set_title('Plain LSTM — Train Loss (MSE, 표준화된 수익률)')",
    "axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Train MSE')",
    "axes[0].legend(); axes[0].grid(alpha=0.3)",
    "",
    "axes[1].set_title('Plain LSTM — Validation Loss')",
    "axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Val MSE')",
    "axes[1].legend(); axes[1].grid(alpha=0.3)",
    "",
    "plt.tight_layout(); plt.show()",
))

cells.append(code(
    "# ---- 파라미터 수 이론값 검증 ----",
    "# nn.LSTM 의 파라미터 수 공식: 4 * (H*H + I*H + H)  per layer  (단, 2번째 이후 층은 I=H 로 교체)",
    "# 최종 head: H + 1 (Linear(H,1): H*1 weight + 1 bias)",
    "",
    "def theoretical_params(input_dim, hidden, num_layers):",
    "    '''nn.LSTM + 선형 헤드 파라미터 수 이론값.'''",
    "    total = 0",
    "    for l in range(num_layers):",
    "        I = input_dim if l == 0 else hidden",
    "        # weight_ih: (4H, I), weight_hh: (4H, H), bias_ih/hh: 각 (4H,)",
    "        total += 4 * hidden * I + 4 * hidden * hidden + 4 * hidden + 4 * hidden",
    "    total += hidden * 1 + 1  # head",
    "    return total",
    "",
    "rows = []",
    "for L in [1, 2, 3]:",
    "    actual = plain_results[L][3]",
    "    theory = theoretical_params(INPUT_DIM, HIDDEN, L)",
    "    rows.append({'num_layers': L, 'actual_params': actual, 'theoretical_params': theory,",
    "                 '일치': '✅' if actual == theory else '❌'})",
    "",
    "pd.DataFrame(rows)",
))

# ---------------------------------------------------------------------------
# §4. 실험 2 — 층별 gradient norm
# ---------------------------------------------------------------------------
cells.append(md(
    "---",
    "",
    "## §4. 실험 2 — 층별 Gradient Norm 관찰 (`weight_hh` 기준)",
    "",
    "**배경:** 깊이를 늘리면 gradient 가 시간축 BPTT 와 깊이축 역전파의 **이중 곱셈** 을 ",
    "거치면서 더 심한 vanishing 을 겪을 수 있다. 이 실험은 그것이 실제로 관측되는지 측정한다.",
    "",
    "### 🔧 측정 대상 선택 — `weight_hh_l*` 를 쓰는 이유",
    "",
    "초기 설계에서는 `weight_ih_l{l}` 의 gradient norm 을 비교했으나, **원소 개수가 층마다 다르다**:",
    "",
    "| 가중치 | 형상 | 원소 수 |",
    "|---|---|---|",
    "| `weight_ih_l0` | `(4H=256, I=10)` | **2,560** |",
    "| `weight_ih_l1` | `(4H=256, H=64)` | 16,384 |",
    "| `weight_ih_l2` | `(4H=256, H=64)` | 16,384 |",
    "",
    "L2 norm 은 **element-wise 제곱합의 루트** 이기 때문에 원소 수가 많을수록 값이 커지는 경향이 있다. ",
    "즉 `weight_ih` 로 측정하면 입력층 `l0` 이 원소 수가 적어 norm 도 작게 나올 수밖에 없어 **공정한 비교가 불가능**하다.",
    "",
    "반면 `weight_hh_l{l}` 은 모든 층에서 **(4H=256, H=64) = 16,384 원소로 동일 형상** 이다. ",
    "따라서 이 실험에서는 `weight_hh_l{l}` 의 gradient norm 을 비교하여 **순수한 깊이축 gradient 흐름만** 관찰한다.",
    "",
    "### 실험 방법",
    "",
    "실험 1 의 3층 모델에 `register_hook` 을 달아 매 역전파마다 각 층의 `weight_hh_l{l}` gradient 의 norm 을 수집 ",
    "→ (a) 에폭별 평균 (b) iteration 단위 시계열 두 가지로 플롯.",
    "",
    "### 기대 패턴",
    "",
    "깊이축 vanishing 이 유효하다면 입력 쪽 층 (`weight_hh_l0`) 의 gradient norm 이 출력 쪽 (`weight_hh_l2`) 보다 **작아야** 한다 ",
    "(= 입력 쪽은 학습이 느리게 진행됨). 다만 MSFT 일일 수익률 태스크는 신호가 약해 gradient 자체가 전반적으로 작고, ",
    "층간 차이가 미미할 가능성도 있다. **결과를 보고 판단**한다.",
))

cells.append(code(
    "# ---- 3층 모델 재학습하면서 층별 grad norm 수집 ----",
    "reset_seed()",
    "model_3 = PlainLSTMRegressor(INPUT_DIM, HIDDEN, num_layers=3).to(device)",
    "optimizer = torch.optim.AdamW(model_3.parameters(), lr=LR, weight_decay=1e-4)",
    "loss_fn = nn.MSELoss()",
    "",
    "# 각 층의 hidden-to-hidden 가중치에 hook 달기 (원소 수 동일 → 공정 비교)",
    "# weight_hh_l{l} 의 형상: 모든 층에서 (4H=256, H=64) = 16,384 원소",
    "grad_norms = {0: [], 1: [], 2: []}  # 층별 iteration 단위 grad norm 기록",
    "",
    "def make_hook(layer_idx):",
    "    def hook(grad):",
    "        # element-wise L2 norm. 형상이 같으므로 층간 직접 비교 가능",
    "        grad_norms[layer_idx].append(grad.norm().item())",
    "    return hook",
    "",
    "for l in range(3):",
    "    # weight_hh_l{l}: hidden-to-hidden 순환 가중치. 모든 층 동일 형상",
    "    getattr(model_3.lstm, f'weight_hh_l{l}').register_hook(make_hook(l))",
    "",
    "# ---- 짧게 10 에폭 학습 ----",
    "# 에폭별 평균과 iteration 단위 전체 시계열을 각각 기록",
    "epoch_mean_norms = {0: [], 1: [], 2: []}",
    "all_iter_norms = {0: [], 1: [], 2: []}  # 모든 iteration 의 원시 기록",
    "",
    "for epoch in range(10):",
    "    # iteration 기록 버퍼 초기화 (에폭 평균 계산용)",
    "    for l in range(3):",
    "        grad_norms[l].clear()",
    "    model_3.train()",
    "    for xb, yb in train_loader:",
    "        xb, yb = xb.to(device), yb.to(device)",
    "        optimizer.zero_grad()",
    "        pred = model_3(xb)",
    "        loss_fn(pred, yb).backward()",
    "        nn.utils.clip_grad_norm_(model_3.parameters(), max_norm=1.0)",
    "        optimizer.step()",
    "    # 에폭 평균 + 전체 iteration 시계열에 누적",
    "    for l in range(3):",
    "        epoch_mean_norms[l].append(float(np.mean(grad_norms[l])) if grad_norms[l] else 0.0)",
    "        all_iter_norms[l].extend(grad_norms[l])  # iteration 단위 원시값 보존",
    "",
    "# 수치 출력 — 에폭별 평균",
    "print('=== 에폭별 평균 gradient norm (weight_hh 기준, 원소 수 동일) ===')",
    "for l in range(3):",
    "    norms = epoch_mean_norms[l]",
    "    print(f'layer {l}: [{\", \".join(f\"{v:.5f}\" for v in norms)}]')",
    "",
    "print(f'\\n총 iteration 기록 수: {len(all_iter_norms[0])}')",
))

cells.append(code(
    "# ---- 층별 gradient norm 시각화 (2패널) ----",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4.5))",
    "",
    "# 왼쪽: 에폭 평균 (추세 파악)",
    "for l in range(3):",
    "    axes[0].plot(epoch_mean_norms[l], marker='o', label=f'layer {l} (weight_hh_l{l})')",
    "axes[0].set_title('에폭별 평균 — Plain 3층 LSTM gradient norm')",
    "axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('평균 gradient norm')",
    "axes[0].set_yscale('log')",
    "axes[0].legend(); axes[0].grid(alpha=0.3)",
    "",
    "# 오른쪽: iteration 시계열 (순간값 분포)",
    "# 원시 시계열은 튀는 값이 많아 스무딩된 이동평균을 함께 표시",
    "window_ma = 20  # 20-iteration 이동평균",
    "for l in range(3):",
    "    series = np.array(all_iter_norms[l])",
    "    axes[1].plot(series, alpha=0.25, label=f'layer {l} (raw)')",
    "    # 이동평균",
    "    if len(series) >= window_ma:",
    "        ma = np.convolve(series, np.ones(window_ma) / window_ma, mode='valid')",
    "        axes[1].plot(np.arange(window_ma - 1, len(series)), ma,",
    "                     linewidth=1.8, label=f'layer {l} (MA-{window_ma})')",
    "axes[1].set_title(f'Iteration 시계열 — {window_ma}-iter 이동평균 겹침')",
    "axes[1].set_xlabel('Iteration (누적)'); axes[1].set_ylabel('gradient norm')",
    "axes[1].set_yscale('log')",
    "axes[1].legend(fontsize=8, ncol=2); axes[1].grid(alpha=0.3)",
    "",
    "plt.tight_layout(); plt.show()",
    "",
    "# ---- 비율 해석 ----",
    "last_epoch = {l: epoch_mean_norms[l][-1] for l in range(3)}",
    "print(f'\\n=== 마지막 에폭 gradient norm ===')",
    "for l in range(3):",
    "    print(f'  layer {l}: {last_epoch[l]:.5f}')",
    "",
    "# 전체 iteration 기준 중앙값 — 튀는 값 영향 최소화",
    "med_norms = {l: float(np.median(all_iter_norms[l])) for l in range(3)}",
    "print(f'\\n=== 전체 iteration 중앙값 (튀는 값 둔감) ===')",
    "for l in range(3):",
    "    print(f'  layer {l}: {med_norms[l]:.5f}')",
    "",
    "print(f'\\n=== 층간 비율 (input → output 방향) ===')",
    "if med_norms[0] > 0:",
    "    r10 = med_norms[1] / med_norms[0]",
    "    r21 = med_norms[2] / med_norms[1]",
    "    r20 = med_norms[2] / med_norms[0]",
    "    print(f'  layer 1 / layer 0 = {r10:.3f}')",
    "    print(f'  layer 2 / layer 1 = {r21:.3f}')",
    "    print(f'  layer 2 / layer 0 = {r20:.3f}')",
    "    print()",
    "    print('해석 가이드:')",
    "    print('  비율 > 1.0  → 출력 쪽 gradient 가 더 큼 (입력 쪽 vanishing 시사)')",
    "    print('  비율 ≈ 1.0  → 깊이축 gradient 흐름 균등 (vanishing 없음)')",
    "    print('  비율 < 1.0  → 입력 쪽 gradient 가 더 큼 (vanishing 반대 — 드물지만 가능)')",
))

# ---------------------------------------------------------------------------
# §5. 실험 3 — VD + 층별 LayerNorm
# ---------------------------------------------------------------------------
cells.append(md(
    "---",
    "",
    "## §5. 실험 3 — Variational Dropout + 층별 LayerNorm 결합",
    "",
    "**3.5 §2·§3 이론의 다층 확장.** 핵심 차이:",
    "",
    "- **Variational Dropout**: 타임스텝 간 mask 공유 (일반 Dropout 은 매 timestep 독립)",
    "- **층별 LayerNorm**: LSTM 출력 `(B, T, H)` 를 층마다 정규화 → covariate shift 누적 방지",
    "- **`nn.ModuleList` 구조**: `nn.LSTM(num_layers=k)` 한 방에 쌓지 않고, 1층씩 따로 쌓아 중간에 LN/VD 삽입 가능",
    "",
    "이 설계는 4.3 Optuna 탐색 시 `StackedLSTMRegressor(num_layers)` 를 그대로 넘길 수 있도록 한다.",
))

cells.append(code(
    "class VariationalDropout(nn.Module):",
    "    '''Gal & Ghahramani (2016) Variational Dropout.",
    "    한 forward 내의 모든 timestep 에 동일한 mask 를 적용 → 시계열 일관성 보존.",
    "    3.5 §2 에서 구현한 것과 동일.'''",
    "    def __init__(self, p: float):",
    "        super().__init__()",
    "        self.p = p",
    "",
    "    def forward(self, x: torch.Tensor) -> torch.Tensor:",
    "        # x: (B, T, H)",
    "        if not self.training or self.p == 0.0:",
    "            return x",
    "        # (B, 1, H) mask — T 축으로 broadcast 되어 모든 timestep 에 동일 적용",
    "        mask_shape = (x.size(0), 1, x.size(2))",
    "        mask = torch.bernoulli(torch.full(mask_shape, 1 - self.p, device=x.device))",
    "        mask = mask / (1 - self.p)  # inverted dropout",
    "        return x * mask",
))

cells.append(code(
    "class RegularizedStackedLSTM(nn.Module):",
    "    '''Variational Dropout + 층별 LayerNorm + AdamW 레시피 결합.",
    "",
    "    구조:",
    "        input",
    "          → VD(p) → LSTM_l0 → LN_l0",
    "          → VD(p) → LSTM_l1 → LN_l1",
    "          → ...",
    "          → last timestep → Linear(H, 1)",
    "",
    "    주의: nn.ModuleList 로 1층씩 쌓아야 중간에 LN/VD 삽입 가능.",
    "    nn.LSTM(num_layers=k) 는 층 사이에 끼워넣을 공간이 없다.'''",
    "",
    "    def __init__(self, input_size, hidden_size, num_layers, dropout=0.2):",
    "        super().__init__()",
    "        self.num_layers = num_layers",
    "",
    "        self.lstms = nn.ModuleList()",
    "        self.lns = nn.ModuleList()",
    "        self.vds = nn.ModuleList()",
    "",
    "        for l in range(num_layers):",
    "            in_dim = input_size if l == 0 else hidden_size",
    "            self.vds.append(VariationalDropout(p=dropout))",
    "            self.lstms.append(nn.LSTM(in_dim, hidden_size, num_layers=1, batch_first=True))",
    "            self.lns.append(nn.LayerNorm(hidden_size))",
    "",
    "        self.final_vd = VariationalDropout(p=dropout)",
    "        self.head = nn.Linear(hidden_size, 1)",
    "",
    "    def forward(self, x):",
    "        # x: (B, T, D)",
    "        out = x",
    "        for l in range(self.num_layers):",
    "            out = self.vds[l](out)            # 층 입력에 VD",
    "            out, _ = self.lstms[l](out)       # 1층 LSTM",
    "            out = self.lns[l](out)            # 층 출력에 LN",
    "        out = self.final_vd(out)              # head 직전 VD",
    "        last = out[:, -1, :]                  # (B, H)",
    "        return self.head(last).squeeze(-1)    # (B,)",
))

cells.append(code(
    "# ---- 정규화 모델 1/2/3층 학습 ----",
    "reg_results = {}",
    "DROPOUT = 0.2",
    "",
    "for L in [1, 2, 3]:",
    "    reset_seed()",
    "    model = RegularizedStackedLSTM(INPUT_DIM, HIDDEN, num_layers=L, dropout=DROPOUT)",
    "    n_params = count_params(model)",
    "    print(f'\\n=== Regularized {L}층 ({n_params:,} params, dropout={DROPOUT}) ===')",
    "    best_val, hist, trained = train_one_individual(model, epochs=EPOCHS, lr=LR, verbose=True)",
    "    reg_results[L] = (best_val, hist, trained, n_params)",
    "",
    "print('\\n=== 실험 3 요약 ===')",
    "for L, (best, hist, _, n_params) in reg_results.items():",
    "    print(f'{L}층 | params={n_params:>7,} | best_val_loss={best:.5f}')",
))

cells.append(code(
    "# ---- 학습곡선 비교 플롯 ----",
    "fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))",
    "",
    "for L, (_, hist, _, _) in reg_results.items():",
    "    tr = [h[0] for h in hist]",
    "    va = [h[1] for h in hist]",
    "    axes[0].plot(tr, label=f'{L}층', alpha=0.85)",
    "    axes[1].plot(va, label=f'{L}층', alpha=0.85)",
    "",
    "axes[0].set_title(f'Regularized LSTM — Train Loss (VD={DROPOUT} + 층별 LN)')",
    "axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Train MSE')",
    "axes[0].legend(); axes[0].grid(alpha=0.3)",
    "",
    "axes[1].set_title('Regularized LSTM — Validation Loss')",
    "axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Val MSE')",
    "axes[1].legend(); axes[1].grid(alpha=0.3)",
    "",
    "plt.tight_layout(); plt.show()",
))

# ---------------------------------------------------------------------------
# §6. 실험 4 — plain vs regularized
# ---------------------------------------------------------------------------
cells.append(md(
    "---",
    "",
    "## §6. 실험 4 — Plain 3층 vs Regularized 3층 직접 비교",
    "",
    "실험 1 · 3 의 3층 학습곡선을 한 판에 겹쳐 그려서 **정규화가 깊이에 주는 효과를 시각적으로 증명**.",
    "",
    "비교 관점:",
    "- **val loss** 최솟값 — 최종 성능",
    "- **train/val gap** — 과적합 정도",
    "- **수렴 안정성** — 학습곡선 진동 여부",
))

cells.append(code(
    "# ---- 3층만 비교 ----",
    "plain_best, plain_hist, *_ = plain_results[3]",
    "reg_best, reg_hist, *_ = reg_results[3]",
    "",
    "fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))",
    "",
    "# 왼쪽: train/val 곡선 (plain)",
    "axes[0].plot([h[0] for h in plain_hist], label='train', color='tab:blue')",
    "axes[0].plot([h[1] for h in plain_hist], label='val', color='tab:orange')",
    "axes[0].set_title(f'Plain 3층 (best_val={plain_best:.5f})')",
    "axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('MSE')",
    "axes[0].legend(); axes[0].grid(alpha=0.3)",
    "",
    "# 오른쪽: train/val 곡선 (regularized)",
    "axes[1].plot([h[0] for h in reg_hist], label='train', color='tab:blue')",
    "axes[1].plot([h[1] for h in reg_hist], label='val', color='tab:orange')",
    "axes[1].set_title(f'Regularized 3층 (best_val={reg_best:.5f})')",
    "axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('MSE')",
    "axes[1].legend(); axes[1].grid(alpha=0.3)",
    "",
    "plt.tight_layout(); plt.show()",
    "",
    "# train/val gap 분석",
    "plain_last_gap = plain_hist[-1][1] - plain_hist[-1][0]  # val - train",
    "reg_last_gap = reg_hist[-1][1] - reg_hist[-1][0]",
    "print(f'\\n마지막 에폭 val-train gap:')",
    "print(f'  Plain 3층     : {plain_last_gap:+.5f} (양수일수록 과적합)')",
    "print(f'  Regularized 3층: {reg_last_gap:+.5f}')",
))

cells.append(code(
    "# ---- 종합 비교 테이블 ----",
    "rows = []",
    "for L in [1, 2, 3]:",
    "    plain_best, plain_hist, _, plain_params = plain_results[L]",
    "    reg_best, reg_hist, _, reg_params = reg_results[L]",
    "    rows.append({",
    "        'num_layers': L,",
    "        'plain_params': plain_params,",
    "        'plain_best_val': round(plain_best, 6),",
    "        'reg_params': reg_params,",
    "        'reg_best_val': round(reg_best, 6),",
    "        'Δ(reg - plain)': round(reg_best - plain_best, 6),",
    "        '정규화 승?': '✅' if reg_best < plain_best else '❌',",
    "    })",
    "",
    "summary = pd.DataFrame(rows)",
    "summary",
))

# ---------------------------------------------------------------------------
# §7. 결론
# ---------------------------------------------------------------------------
cells.append(md(
    "---",
    "",
    "## §7. 결론 + CEEMDAN IMF 깊이 가설",
    "",
    "### §3/§5/§6 관측 결과 (val loss 비교)",
    "",
    "| 실험 | 결과 요약 |",
    "|---|---|",
    "| §3 실험 1 | 1층 `best_val=1.17706`, 2층 `1.17511`, 3층 `1.17449`. **단조 감소지만 차이가 극미** (~0.002). 깊이 증가가 val 에 약간이나마 이득, 이론값 대비 파라미터 수 완전 일치 |",
    "| §5 실험 3 | 1층 `1.17179`, 2층 `1.17176`, 3층 `1.16953`. **Regularized 에서도 3층이 가장 우수** — VD+LN 이 깊이 확장을 가능하게 함 |",
    "| §6 실험 4 | 모든 L 에서 Regularized > Plain (Δ = −0.003 ~ −0.005). 정규화의 효과는 모든 깊이에서 일관됨 |",
    "",
    "### §4 실험 2 — 층별 Gradient Norm 실측 결과",
    "",
    "#### 왜곡 해소 확인 (원소 수 보정 효과)",
    "",
    "| 측정 기준 | layer 2 / layer 0 비율 | 해석 |",
    "|---|---|---|",
    "| `weight_ih` (1차, 원소 수 불균형) | ~0.11 | layer 0 이 9배 커 보임 (측정 왜곡) |",
    "| `weight_hh` (재측정, 모든 층 16,384 원소) | **0.840** | 진정한 층간 비율 관찰 |",
    "",
    "→ 원소 수를 동등하게 맞추니 층간 비율이 **극적으로 완화**. 1차 결과의 9배 격차는 측정 왜곡이었음이 실증됨.",
    "",
    "#### 3층 MSFT 태스크 측정값 (최종 실행 — 총 470 iteration)",
    "",
    "| Layer | 마지막 에폭 평균 | 전체 iteration 중앙값 |",
    "|---|---|---|",
    "| layer 0 (입력 쪽) | **0.09093** | 0.02078 |",
    "| layer 1 (중간) | 0.03897 | **0.01188** |",
    "| layer 2 (출력 쪽) | 0.03452 | 0.01746 |",
    "",
    "| 층간 비율 | 값 | 의미 |",
    "|---|---|---|",
    "| layer 1 / layer 0 | 0.572 | 중간층이 입력층의 57% — 중간에서 줄어듦 |",
    "| layer 2 / layer 1 | 1.470 | 출력층이 중간층의 1.47배 — 중간에서 다시 회복 |",
    "| layer 2 / layer 0 | 0.840 | 출력층은 입력층의 84% — **3층 규모에서는 vanishing 약함** |",
    "",
    "#### 관측 결과 3가지",
    "",
    "1. **layer 0 이 여전히 가장 큼 (0.091)** — 입력 피처의 유효 규모가 gradient 에 반영된 것. 이론상 입력 쪽 vanishing 과 반대 방향이지만, **3층 규모에서는 vanishing 이 파괴적이지 않음**을 시사.",
    "2. **중앙값 기준 layer 1 이 가장 작은 U자형** (0.021 → 0.012 → 0.017) — Pascanu et al. (2013) §7 의 **중간층 bottleneck** 패턴과 일치. 중간층이 양쪽으로부터 부담을 나눠 가지며 가장 얇은 통로가 됨.",
    "3. **layer 2 / layer 0 = 0.84 → vanishing 약함** — 3층 수준에서는 깊이축 vanishing 이 극적이지 않다. 파괴적 vanishing 은 보통 **6층 이상**에서 관측. 본 실습의 3층 설정에서는 'vanishing 실증' 이 아니라 **'공정한 층별 측정 프로토콜 수립'** 이 본래 교훈.",
    "",
    "#### 4.3 OLSTM 탐색에 주는 시사점",
    "",
    "- `num_layers` ∈ {1, 2, 3} 범위는 **vanishing 걱정 없이 안전하게 탐색 가능** — 3층도 gradient 가 충분히 흐름 (layer 2/0 = 0.84)",
    "- 만약 5층 이상으로 확장 시 **VD + LN 의 중요성이 급증** — 정규화 없이는 중간층 bottleneck 이 심화될 것",
    "- 중간층 gradient 가 가장 작은 것은 **버그가 아닌 정상 학습 동역학** — U자형 패턴은 stacked RNN 의 자연스러운 특성",
    "",
    "### ⚠ val loss > 1.0 의 의미 — 솔직한 해석",
    "",
    "모든 실험의 best_val_loss 가 **1.17 근처**에 뭉쳐 있다는 사실은 다음을 뜻한다:",
    "",
    "- 타겟 `y` 는 train 통계로 표준화 → 분산 = 1.0",
    "- \"모두 0 예측\" 모델의 MSE = 1.0 (baseline)",
    "- **`val_loss = 1.17 > 1.0` → 모델이 val 구간에서 baseline 보다 나쁨**",
    "",
    "즉 모델이 train 에는 약간 fit 하지만 **val 일반화는 실패**하고 있다. 이는:",
    "",
    "1. **MSFT 일일 수익률은 near-random-walk** — 10차원 간이 피처 + 60일 lookback 만으로는 예측력이 안 나오는 것이 정상",
    "2. **이 실습의 본래 목적은 예측력이 아닌 학습 동역학 관찰** — 깊이·정규화가 val loss 에 **어떤 방향으로** 영향을 주는지 비교하는 것",
    "3. **CEEMDAN 분해 후 IMF 별 학습** (Week 4.3~5.1) 단계에서 실질 예측력 개선 기대",
    "",
    "따라서 val loss 의 **절대값이 아닌 조건 간 차이의 방향성** 이 본 실습의 핵심 메시지다.",
    "",
    "### 4.3 Optuna 탐색을 위한 사전 가설",
    "",
    "| IMF 특성 | 추천 `num_layers` | 추천 `dropout` | 근거 |",
    "|---|---|---|---|",
    "| **고주파 IMF (IMF1~2)** — 노이즈 성격 | 1~2 | 0.3~0.5 | 모델링할 구조가 적음. 깊이 대신 정규화로 과적합만 막기 |",
    "| **중주파 IMF (IMF3~5)** — 단기 패턴 | 2~3 | 0.1~0.3 | 적절한 비선형성 필요 |",
    "| **저주파 IMF (IMF6~10)** — 추세 성격 | 2~3 + 강한 정규화 | 0.2~0.4 | 긴 의존성 + 과적합 위험. 3층 시 반드시 VD+LN |",
    "",
    "→ 이 가설은 Week 4.3 Optuna 탐색 시 **`num_layers` 를 categorical 로 [1,2,3] 전체 탐색** 하여 검증한다. ",
    "만약 Optuna 가 IMF 에 따라 다른 `num_layers` 를 선택한다면 가설 입증. 모든 IMF 에서 `num_layers=1` 을 고른다면 ",
    "ETF 규모에서는 깊이가 불필요하다는 결론으로 간다. (Week 4.3 부터 데이터가 MSFT → XLK 섹터 ETF 로 전환 예정)",
    "",
    "### 체크포인트",
    "",
    "- [x] Plain 1/2/3층 학습곡선 비교 (§3)",
    "- [x] 층별 gradient norm 관측 (§4) — `weight_hh` 재측정 완료, layer 2/0 = 0.84",
    "- [x] Variational Dropout + 층별 LayerNorm 결합 1/2/3층 비교 (§5)",
    "- [x] Plain vs Regularized 3층 직접 비교 (§6)",
    "- [x] **로컬 실행 검증 완료** — §3/§5/§6 val loss · §4 gradient norm 실측값 모두 확보",
    "",
    "### 다음 토픽",
    "",
    "- **4.2 BiLSTM (양방향 LSTM)** — 순방향 + 역방향 hidden concat. 시계열 Walk-Forward 에서의 look-ahead 주의점",
    "- **4.3 OLSTM (Optuna-LSTM)** ⭐ — 이 노트북에서 만든 `RegularizedStackedLSTM` 을 Optuna objective 로 감싸 IMF 별 최적 HP 탐색",
    "  - 이 시점에서 데이터 소스를 **MSFT → XLK (Technology 섹터 SPDR ETF)** 로 전환",
))

# ---------------------------------------------------------------------------
# 조립 + 저장
# ---------------------------------------------------------------------------
nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.11",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

# 저장 경로 — Linux 샌드박스 실행 기준.
# Windows `C:\...\` 경로를 Path() 에 그대로 넘기면 Linux 는 백슬래시를 파일명 문자로 취급해
# 하나의 긴 파일명이 생긴다. 이 스크립트는 항상 스크립트 자신이 놓인 디렉토리에 저장.
out = Path(__file__).parent / "01_StackedLSTM_실습.ipynb"
out.parent.mkdir(parents=True, exist_ok=True)
with out.open("w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

# 셀 수 / 코드 셀 구문 검증
import ast
code_cells = [c for c in cells if c["cell_type"] == "code"]
print(f"총 셀 수      : {len(cells)}")
print(f"코드 셀 수    : {len(code_cells)}")
print(f"마크다운 셀 수: {len(cells) - len(code_cells)}")

errors = 0
for i, c in enumerate(code_cells):
    try:
        ast.parse(c["source"])
    except SyntaxError as e:
        print(f"❌ code cell {i} SyntaxError: {e}")
        errors += 1
print(f"\n파일 저장    : {out}")
print(f"파일 크기    : {out.stat().st_size:,} bytes")
print(f"구문 오류    : {errors} / {len(code_cells)}")
